# Generated by Django 4.1.2 on 2023-02-09 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Statistic",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("station", models.CharField(blank=True, max_length=200, null=True)),
                ("weather_date", models.DateField(blank=True, null=True)),
                ("final_max_temp", models.IntegerField(blank=True, null=True)),
                ("final_mini_temp", models.IntegerField(blank=True, null=True)),
                ("final_precip", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "statistic",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Weather",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("station", models.CharField(blank=True, max_length=200, null=True)),
                ("weather_date", models.DateField(blank=True, null=True)),
                ("maximum_temperature", models.IntegerField(blank=True, null=True)),
                ("minimum_temperature", models.IntegerField(blank=True, null=True)),
                ("precipitation", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "weather",
                "managed": False,
            },
        ),
    ]
